import type { EcfCatalogEvent, EcfEventCategory } from '../types'
import { CA4_ECF_EVENTS_URL, ca4SourceVersionIds } from '../rules/ca4-source-profile'
const rulesAndEcfSources = [
  ca4SourceVersionIds.frap2025,
  ca4SourceVersionIds.ca4LocalRules2026,
  ca4SourceVersionIds.ca4EcfEvents2026,
]

export const ca4EcfCatalogEvents: EcfCatalogEvent[] = [
  {
    eventId: 'notice_of_appeal',
    courtEventName: 'Notice of Appeal',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Notice of Appeal'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'feePaymentStatus', 'certificateOfService'],
    requiredDocuments: ['Notice of appeal PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'required',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'criminal_notice_of_appeal',
    courtEventName: 'Notice of Appeal - Criminal',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Notice of Appeal'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Criminal notice of appeal PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'petition_for_review',
    courtEventName: 'Petition for review',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Petition for review'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'feePaymentStatus', 'certificateOfService'],
    requiredDocuments: ['Petition for review PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'required',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'petition_for_writ_mandamus',
    courtEventName: 'Petition for writ of mandamus/prohibition',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Petition for writ of mandamus/prohibition'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'feePaymentStatus', 'certificateOfService'],
    requiredDocuments: ['Writ petition PDF'],
    serviceBehavior: 'mixed',
    feeBehavior: 'required',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'appearance_disclosure',
    courtEventName: 'Appearance of counsel / Disclosure statement',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Appearance of counsel'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Disclosure statement PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'docketing_statement',
    courtEventName: 'Docketing statement (civil/agency)',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Docketing statement (civil/agency)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Docketing statement PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'criminal_docketing_statement',
    courtEventName: 'Docketing statement (criminal)',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Docketing statement (criminal)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Criminal docketing statement PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'agency_docketing_statement',
    courtEventName: 'Docketing statement (civil/agency)',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Docketing statement (civil/agency)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Agency-review docketing statement PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'writ_docketing_statement',
    courtEventName: 'Docketing statement',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Docketing statement'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Writ docketing statement PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'cja_financial_disclosure',
    courtEventName: 'CJA financial disclosure',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'CJA financial disclosure'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['CJA financial disclosure PDF'],
    serviceBehavior: 'manual_required',
    feeBehavior: 'none',
    sealedBehavior: 'manual_review',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'transcript_order_acknowledgment',
    courtEventName: 'Transcript order form',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Transcript order form'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Transcript order acknowledgment PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'certified_agency_record',
    courtEventName: 'Administrative record (electronic form)',
    category: 'Briefing Documents',
    menuPath: ['Briefing Documents', 'Administrative record (electronic form)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Certified agency record PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'motion',
    courtEventName: 'MOTION',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'MOTION'],
    reliefs: ['extend time', 'dismiss', 'remand', 'seal', 'stay', 'other procedural relief'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'reliefRequested', 'certificateOfService'],
    requiredDocuments: ['Motion PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'motion_response',
    courtEventName: 'RESPONSE/ANSWER (to motion or request)',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'RESPONSE/ANSWER (to motion or request)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'relatedDocketEntryId', 'certificateOfService'],
    requiredDocuments: ['Response PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'motion_stay_pending_appeal',
    courtEventName: 'MOTION',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'MOTION', 'Stay or injunction pending appeal'],
    reliefs: ['stay pending appeal', 'injunction pending appeal'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'reliefRequested', 'relatedDocketEntryId', 'certificateOfService'],
    requiredDocuments: ['Stay pending appeal motion PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'motion_to_supplement_record',
    courtEventName: 'MOTION',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'MOTION', 'Supplement record'],
    reliefs: ['supplement record'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'reliefRequested', 'relatedDocketEntryId', 'certificateOfService'],
    requiredDocuments: ['Motion to supplement record PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'emergency_motion_stay',
    courtEventName: 'MOTION',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'MOTION', 'Emergency relief'],
    reliefs: ['emergency stay', 'temporary stay pending writ'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'reliefRequested', 'certificateOfService'],
    requiredDocuments: ['Emergency stay motion PDF'],
    serviceBehavior: 'mixed',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'opening_brief',
    courtEventName: 'BRIEF (formal briefs not under seal)',
    category: 'Briefing Documents',
    menuPath: ['Briefing Documents', 'BRIEF (formal briefs not under seal)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService', 'certificateOfCompliance'],
    requiredDocuments: ['Opening brief PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'joint_appendix',
    courtEventName: 'Joint Appendix',
    category: 'Briefing Documents',
    menuPath: ['Briefing Documents', 'Joint Appendix'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Joint appendix PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'appendix_to_writ_petition',
    courtEventName: 'Appendix to writ petition',
    category: 'Other Filings',
    menuPath: ['Other Filings', 'Appendix to writ petition'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Writ appendix PDF'],
    serviceBehavior: 'mixed',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'appellee_brief',
    courtEventName: 'BRIEF (formal briefs not under seal)',
    category: 'Briefing Documents',
    menuPath: ['Briefing Documents', 'BRIEF (formal briefs not under seal)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService', 'certificateOfCompliance'],
    requiredDocuments: ['Appellee brief PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'reply_brief',
    courtEventName: 'BRIEF (formal briefs not under seal)',
    category: 'Briefing Documents',
    menuPath: ['Briefing Documents', 'BRIEF (formal briefs not under seal)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService', 'certificateOfCompliance'],
    requiredDocuments: ['Reply brief PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'amicus_notice_or_consent',
    courtEventName: 'Notice / Consent statement',
    category: 'Forms, Notices & Filing Fees',
    menuPath: ['Forms, Notices & Filing Fees', 'Notice / Consent statement'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'consentStatus', 'certificateOfService'],
    requiredDocuments: ['Amicus consent or notice PDF'],
    serviceBehavior: 'mixed',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'motion_for_leave_to_file_amicus',
    courtEventName: 'MOTION',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'MOTION', 'Leave to file amicus brief'],
    reliefs: ['leave to file amicus brief'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'reliefRequested', 'consentStatus', 'certificateOfService'],
    requiredDocuments: ['Motion for leave PDF', 'Proposed amicus brief PDF'],
    serviceBehavior: 'mixed',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'response_to_amicus_motion',
    courtEventName: 'RESPONSE/ANSWER (to motion or request)',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'RESPONSE/ANSWER (to motion or request)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'relatedDocketEntryId', 'certificateOfService'],
    requiredDocuments: ['Response to amicus motion PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'order_inviting_answer',
    courtEventName: 'Court order inviting answer',
    category: 'Other Filings',
    menuPath: ['Other Filings', 'Court order inviting answer'],
    reliefs: [],
    requiredFields: [],
    requiredDocuments: ['Order inviting answer PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'answer_to_writ_petition',
    courtEventName: 'RESPONSE/ANSWER (to motion or request)',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'RESPONSE/ANSWER (to motion or request)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'relatedDocketEntryId', 'certificateOfService'],
    requiredDocuments: ['Answer to writ petition PDF'],
    serviceBehavior: 'mixed',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'reply_in_support_of_writ',
    courtEventName: 'Reply in support of writ petition',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'REPLY (to response/answer)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'relatedDocketEntryId', 'certificateOfService'],
    requiredDocuments: ['Reply in support of writ PDF'],
    serviceBehavior: 'mixed',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'amicus_brief',
    courtEventName: 'Amicus Curiae/Intervenor Brief',
    category: 'Briefing Documents',
    menuPath: ['Briefing Documents', 'Amicus Curiae/Intervenor Brief'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'consentStatus', 'certificateOfService', 'certificateOfCompliance'],
    requiredDocuments: ['Amicus brief PDF'],
    serviceBehavior: 'mixed',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'corrected_brief',
    courtEventName: 'Corrected Brief',
    category: 'Briefing Documents',
    menuPath: ['Briefing Documents', 'Corrected Brief'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'relatedDocketEntryId', 'certificateOfService', 'certificateOfCompliance'],
    requiredDocuments: ['Corrected brief PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'rule_28j_letter',
    courtEventName: 'Rule 28(j) letter',
    category: 'Briefing Documents',
    menuPath: ['Briefing Documents', 'Supplemental authorities'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Rule 28(j) letter PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'motion_extend_time',
    courtEventName: 'MOTION',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'MOTION', 'Extend time'],
    reliefs: ['extend time'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'reliefRequested', 'relatedDocketEntryId', 'certificateOfService'],
    requiredDocuments: ['Extension motion PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'motion_overlength_brief',
    courtEventName: 'MOTION',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'MOTION', 'File overlength brief'],
    reliefs: ['file overlength brief'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'reliefRequested', 'certificateOfService'],
    requiredDocuments: ['Overlength motion PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'motion_to_seal',
    courtEventName: 'MOTION',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'MOTION', 'Seal'],
    reliefs: ['seal', 'file under seal'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'reliefRequested', 'sealed', 'sealedDocumentType', 'privacyAcknowledged', 'publicRedactedVersionIncluded', 'certificateOfService'],
    requiredDocuments: ['Motion to seal PDF', 'Proposed sealed material PDF'],
    serviceBehavior: 'manual_required',
    feeBehavior: 'none',
    sealedBehavior: 'public_redacted_required',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'sealed_filing_acknowledgment',
    courtEventName: 'SEALED DOCUMENT (court access only)',
    category: 'Other Filings',
    menuPath: ['Other Filings', 'SEALED DOCUMENT (court access only)'],
    reliefs: [],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'sealed', 'sealedDocumentType', 'privacyAcknowledged', 'certificateOfService'],
    requiredDocuments: ['Sealed filing acknowledgment PDF'],
    serviceBehavior: 'manual_required',
    feeBehavior: 'none',
    sealedBehavior: 'manual_review',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'petition_rehearing',
    courtEventName: 'Petition for rehearing by panel or en banc',
    category: 'Rehearing Petitions & Answers',
    menuPath: ['Rehearing Petitions & Answers', 'Petition for rehearing by panel or en banc'],
    reliefs: ['panel rehearing', 'rehearing en banc'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService', 'certificateOfCompliance'],
    requiredDocuments: ['Rehearing petition PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'mandate_stay_motion',
    courtEventName: 'MOTION',
    category: 'Motions, Responses & Replies',
    menuPath: ['Motions, Responses & Replies', 'MOTION', 'Stay mandate'],
    reliefs: ['stay mandate'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'reliefRequested', 'relatedDocketEntryId', 'certificateOfService'],
    requiredDocuments: ['Motion to stay mandate PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'bill_of_costs',
    courtEventName: 'Bill of Costs',
    category: 'Bills of Cost & Objections',
    menuPath: ['Bills of Cost & Objections', 'Bill of Costs'],
    reliefs: ['tax costs'],
    requiredFields: ['filingAttorneyName', 'representedPartyId', 'certificateOfService'],
    requiredDocuments: ['Bill of costs PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
  {
    eventId: 'writ_disposition',
    courtEventName: 'Writ disposition',
    category: 'Judgments',
    menuPath: ['Judgments', 'Writ disposition'],
    reliefs: ['deny petition', 'grant petition', 'dismiss petition'],
    requiredFields: [],
    requiredDocuments: ['Writ disposition PDF'],
    serviceBehavior: 'cm_ecf',
    feeBehavior: 'none',
    sealedBehavior: 'public',
    sourceVersionIds: rulesAndEcfSources,
  },
]

export const ca4EcfCatalogByEventId = new Map(
  ca4EcfCatalogEvents.map((event) => [event.eventId, event]),
)

export function getCa4EcfCatalogEvent(eventId: string) {
  return ca4EcfCatalogByEventId.get(eventId)
}

export function ecfCategoryFromCatalog(category: EcfCatalogEvent['category']): EcfEventCategory {
  if (category === 'Forms, Notices & Filing Fees') return 'appearance'
  if (category === 'Motions, Responses & Replies') return 'motion'
  if (category === 'Briefing Documents') return 'brief'
  if (category === 'Rehearing Petitions & Answers') return 'post_disposition'
  if (category === 'Bills of Cost & Objections') return 'post_disposition'
  if (category === 'Judgments') return 'post_disposition'
  return 'motion'
}

export function sourceUrlForCa4EcfCatalogEvent(eventId: string) {
  return getCa4EcfCatalogEvent(eventId) ? CA4_ECF_EVENTS_URL : undefined
}

export { CA4_ECF_EVENTS_URL }
