/*
 * Appellate Practice Simulator — federal appellate procedure training.
 * Copyright (C) 2026 Rhajune Park
 * SPDX-License-Identifier: AGPL-3.0-or-later
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

import { ca4SourceVersionIds } from '../../domain/rules/ca4-source-profile'

export type Ca4FormTemplate = {
  id: string
  label: string
  category: string
  fileName: string
  sourceUrl: string
  mediaType: 'application/pdf'
  sourceVersionId: string
}

export const ca4FormTemplates = [
  {
    id: "ca4-notice-of-appeal-from-district-court-01",
    label: "Notice of Appeal from District Court",
    category: "Notice of Appeal & Petition for Review",
    fileName: "01-notice-of-appeal-from-district-court.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/noadc.pdf?sfvrsn=773a8f0d_20",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-notice-of-appeal-in-bankruptcy-case-02",
    label: "Notice of Appeal in Bankruptcy Case",
    category: "Notice of Appeal & Petition for Review",
    fileName: "02-notice-of-appeal-in-bankruptcy-case.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/nobank.pdf?sfvrsn=280464a_22",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-notice-of-appeal-from-tax-court-03",
    label: "Notice of Appeal from Tax Court",
    category: "Notice of Appeal & Petition for Review",
    fileName: "03-notice-of-appeal-from-tax-court.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/noatax.pdf?sfvrsn=1b83fee8_22",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-petition-for-review-of-order-of-agency-board-commission-or-officer-04",
    label: "Petition for Review of Order of Agency, Board, Commission or Officer",
    category: "Notice of Appeal & Petition for Review",
    fileName: "04-petition-for-review-of-order-of-agency-board-commission-or-officer.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/petrvw.pdf?sfvrsn=7d2a7de7_12",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-declaration-of-inmate-filing-05",
    label: "Declaration of Inmate Filing",
    category: "Notice of Appeal & Petition for Review",
    fileName: "05-declaration-of-inmate-filing.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/declarationinmatefiling.pdf?sfvrsn=5a52a509_24",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-application-for-admission-to-the-bar-06",
    label: "Application for Admission to the Bar",
    category: "Attorney Admission, ECF Registration, Address Change",
    fileName: "06-application-for-admission-to-the-bar.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/attyadm.pdf?sfvrsn=4d5ab209_9",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-certificate-of-good-standing-07",
    label: "Certificate of Good Standing",
    category: "Attorney Admission, ECF Registration, Address Change",
    fileName: "07-certificate-of-good-standing.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/certificategoodstandingrequest.pdf?sfvrsn=cad7c195_22",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-disciplinary-history-letter-request-08",
    label: "Disciplinary History Letter Request",
    category: "Attorney Admission, ECF Registration, Address Change",
    fileName: "08-disciplinary-history-letter-request.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/disciplinaryletterrequest.pdf?sfvrsn=7e02b609_2",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-duplicate-admission-certificate-09",
    label: "Duplicate Admission Certificate",
    category: "Attorney Admission, ECF Registration, Address Change",
    fileName: "09-duplicate-admission-certificate.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/duplicateadmissioncertificate.pdf?sfvrsn=e5c3f7ba_12",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-registration-of-previous-bar-admission-10",
    label: "Registration of Previous Bar Admission",
    category: "Attorney Admission, ECF Registration, Address Change",
    fileName: "10-registration-of-previous-bar-admission.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/attyregform.pdf?sfvrsn=dc890d0a_10",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-change-of-address-form-11",
    label: "Change of Address Form",
    category: "Attorney Admission, ECF Registration, Address Change",
    fileName: "11-change-of-address-form.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/changeofaddressform(prose).pdf?sfvrsn=e44f929c_10",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-change-of-address-form-12",
    label: "Change of Address Form",
    category: "Attorney Admission, ECF Registration, Address Change",
    fileName: "12-change-of-address-form.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/changeofaddressform.pdf?sfvrsn=bddd54c0_22",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-appearance-of-counsel-13",
    label: "Appearance of Counsel",
    category: "Appearance, Disclosure, Docketing Statements",
    fileName: "13-appearance-of-counsel.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cor.pdf?sfvrsn=7747bb4a_28",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-appearance-of-qualified-law-student-14",
    label: "Appearance of Qualified Law Student",
    category: "Appearance, Disclosure, Docketing Statements",
    fileName: "14-appearance-of-qualified-law-student.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/appearanceofqualifiedlawstudent.pdf?sfvrsn=79325068_4",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-disclosure-statement-15",
    label: "Disclosure Statement",
    category: "Appearance, Disclosure, Docketing Statements",
    fileName: "15-disclosure-statement.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/discl.pdf?sfvrsn=e8b14186_14",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-docketing-statement-civil-agency-cases-16",
    label: "Docketing Statement (Civil/Agency Cases)",
    category: "Appearance, Disclosure, Docketing Statements",
    fileName: "16-docketing-statement-civil-agency-cases.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/dockstatementcivagy.pdf?sfvrsn=a84490d0_20",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-docketing-statement-criminal-cases-17",
    label: "Docketing Statement (Criminal Cases)",
    category: "Appearance, Disclosure, Docketing Statements",
    fileName: "17-docketing-statement-criminal-cases.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/dockstatementcrim.pdf?sfvrsn=d30321ab_16",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-response-similar-cases-18",
    label: "Response - Similar Cases",
    category: "Appearance, Disclosure, Docketing Statements",
    fileName: "18-response-similar-cases.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/response-similar-cases.pdf?sfvrsn=79b8b709_8",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-appellate-panel-application-19",
    label: "CJA Appellate Panel Application",
    category: "CJA & Assigned Counsel",
    fileName: "19-cja-appellate-panel-application.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cjaappellatepanelapplicationform.pdf?sfvrsn=d5e8c3_50",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-appellate-panel-renewal-application-20",
    label: "CJA Appellate Panel Renewal Application",
    category: "CJA & Assigned Counsel",
    fileName: "20-cja-appellate-panel-renewal-application.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/CJAappellatePanelRenewalForm.pdf?sfvrsn=9efaa8a_36",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-20-payment-memo-21",
    label: "CJA 20 Payment Memo",
    category: "CJA & Assigned Counsel",
    fileName: "21-cja-20-payment-memo.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cjapayment20.pdf?sfvrsn=728db109_15",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-20-worksheets-22",
    label: "CJA 20 Worksheets",
    category: "CJA & Assigned Counsel",
    fileName: "22-cja-20-worksheets.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cja20worksheets.pdf?sfvrsn=b1f3e5ab_20",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-30-payment-memo-23",
    label: "CJA 30 Payment Memo",
    category: "CJA & Assigned Counsel",
    fileName: "23-cja-30-payment-memo.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cjapayment30.pdf?sfvrsn=2c3dde20_141",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-30-worksheets-24",
    label: "CJA 30 Worksheets",
    category: "CJA & Assigned Counsel",
    fileName: "24-cja-30-worksheets.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cja30worksheets.pdf?sfvrsn=3f950c25_12",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-associate-counsel-25",
    label: "Associate Counsel",
    category: "CJA & Assigned Counsel",
    fileName: "25-associate-counsel.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cjaauthorizationrequestform-associatecounsel.pdf?sfvrsn=1963b809_8",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-authorization-request-form-combined-service-providers-exceeding-1000-26",
    label: "CJA Authorization Request Form-Combined Service Providers Exceeding $1000",
    category: "CJA & Assigned Counsel",
    fileName: "26-cja-authorization-request-form-combined-service-providers-exceeding-1000.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cjaauthorizationrequestform-combinedservicesexceed1000.pdf?sfvrsn=2cabb109_7",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-travel-27",
    label: "Travel",
    category: "CJA & Assigned Counsel",
    fileName: "27-travel.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cjaauthorizationrequestform-travel.pdf?sfvrsn=463b809_10",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-assigned-counsel-payment-memo-28",
    label: "Assigned Counsel Payment Memo",
    category: "CJA & Assigned Counsel",
    fileName: "28-assigned-counsel-payment-memo.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/assignedpayment.pdf?sfvrsn=34b46208_85",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-assigned-counsel-voucher-29",
    label: "Assigned Counsel Voucher",
    category: "CJA & Assigned Counsel",
    fileName: "29-assigned-counsel-voucher.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/assignedvoucher.pdf?sfvrsn=a3c99f65_18",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-assigned-counsel-worksheets-30",
    label: "Assigned Counsel Worksheets",
    category: "CJA & Assigned Counsel",
    fileName: "30-assigned-counsel-worksheets.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/assignedworksheets.pdf?sfvrsn=4194fa93_10",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-assigned-counsel-printer-voucher-31",
    label: "Assigned Counsel Printer Voucher",
    category: "CJA & Assigned Counsel",
    fileName: "31-assigned-counsel-printer-voucher.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/assignedvoucherprinter.pdf?sfvrsn=5a24734b_24",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-certificate-of-death-penalty-case-32",
    label: "Certificate of Death Penalty Case",
    category: "CJA & Assigned Counsel",
    fileName: "32-certificate-of-death-penalty-case.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/LR22bCertificate.pdf?sfvrsn=609a6822_4",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-certiorari-status-form-33",
    label: "Certiorari Status Form",
    category: "CJA & Assigned Counsel",
    fileName: "33-certiorari-status-form.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/certioraristatusform.pdf?sfvrsn=f7bb02a4_35",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-21-paralegal-worksheet-34",
    label: "CJA 21 Paralegal Worksheet",
    category: "CJA & Assigned Counsel",
    fileName: "34-cja-21-paralegal-worksheet.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cjaparalegalworksheet.pdf?sfvrsn=f4e8ac09_22",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-23-financial-affidavit-35",
    label: "CJA 23 Financial Affidavit",
    category: "CJA & Assigned Counsel",
    fileName: "35-cja-23-financial-affidavit.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cja23affidavit.pdf?sfvrsn=166f104d_26",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-31-paralegal-worksheet-36",
    label: "CJA 31 Paralegal Worksheet",
    category: "CJA & Assigned Counsel",
    fileName: "36-cja-31-paralegal-worksheet.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cja31paralegalworksheet.pdf?sfvrsn=236ae09_18",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-taxpayer-identification-form-37",
    label: "CJA Taxpayer Identification Form",
    category: "CJA & Assigned Counsel",
    fileName: "37-cja-taxpayer-identification-form.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/cjataxpayeridentificationform.pdf?sfvrsn=d31b0d0a_10",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-cja-travel-notice-38",
    label: "CJA Travel Notice",
    category: "CJA & Assigned Counsel",
    fileName: "38-cja-travel-notice.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/tvlflyer.pdf?sfvrsn=2efb6137_23",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-in-forma-pauperis-affidavit-39",
    label: "In Forma Pauperis Affidavit",
    category: "IFP, CJA and PLRA",
    fileName: "39-in-forma-pauperis-affidavit.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/ifpapp.pdf?sfvrsn=4feffbae_18",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-prison-litigation-reform-act-application-40",
    label: "Prison Litigation Reform Act Application",
    category: "IFP, CJA and PLRA",
    fileName: "40-prison-litigation-reform-act-application.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/plraapplication.pdf?sfvrsn=fd589ca6_22",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-prison-litigation-reform-act-consent-to-collection-of-fees-for-appeal-41",
    label: "Prison Litigation Reform Act Consent to Collection of Fees (for appeal)",
    category: "IFP, CJA and PLRA",
    fileName: "41-prison-litigation-reform-act-consent-to-collection-of-fees-for-appeal.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/PLRAConsentFormCVCVRGTOTHR.pdf?sfvrsn=e68a04f3_18",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-prison-litigation-reform-act-consent-to-collection-of-fees-for-mandamus-42",
    label: "Prison Litigation Reform Act Consent to Collection of Fees (for mandamus)",
    category: "IFP, CJA and PLRA",
    fileName: "42-prison-litigation-reform-act-consent-to-collection-of-fees-for-mandamus.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/PLRAConsentFormOP.pdf?sfvrsn=17232d94_22",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-prisoner-trust-account-statement-43",
    label: "Prisoner Trust Account Statement",
    category: "IFP, CJA and PLRA",
    fileName: "43-prisoner-trust-account-statement.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/PLRATrustAccountForm.pdf?sfvrsn=b4284131_12",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-transcript-order-form-44",
    label: "Transcript Order Form",
    category: "Transcripts",
    fileName: "44-transcript-order-form.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/tpo.pdf?sfvrsn=7fd80ad3_47",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-transcript-information-sheet-45",
    label: "Transcript Information Sheet",
    category: "Transcripts",
    fileName: "45-transcript-information-sheet.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/transcriptinformationsheet.pdf?sfvrsn=31abb009_5",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-transcript-authorizations-and-cja-24-vouchers-46",
    label: "Transcript Authorizations and CJA 24 Vouchers",
    category: "Transcripts",
    fileName: "46-transcript-authorizations-and-cja-24-vouchers.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/TranscriptAuthorizationsandVouchers.pdf?sfvrsn=5a32aa09_18",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-transcript-order-deficiency-notice-47",
    label: "Transcript Order Deficiency Notice",
    category: "Transcripts",
    fileName: "47-transcript-order-deficiency-notice.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/deficienttpo.pdf?sfvrsn=dcc4c312_13",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-transcript-extension-request-48",
    label: "Transcript Extension Request",
    category: "Transcripts",
    fileName: "48-transcript-extension-request.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/courtreporterextensionrequest.pdf?sfvrsn=f8f152ea_11",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-transcript-certification-of-filing-sanction-49",
    label: "Transcript Certification of Filing/Sanction",
    category: "Transcripts",
    fileName: "49-transcript-certification-of-filing-sanction.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/certfilingtranscript.pdf?sfvrsn=7fc88dd2_20",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-transcript-guidelines-50",
    label: "Transcript Guidelines",
    category: "Transcripts",
    fileName: "50-transcript-guidelines.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/transgdl.pdf?sfvrsn=135225c1_14",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-certificate-of-confidentiality-51",
    label: "Certificate of Confidentiality",
    category: "Sealed Material",
    fileName: "51-certificate-of-confidentiality.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/CertifConf.pdf?sfvrsn=60def7d1_18",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-certificate-for-highly-sensitive-document-protection-52",
    label: "Certificate for Highly Sensitive Document Protection",
    category: "Sealed Material",
    fileName: "52-certificate-for-highly-sensitive-document-protection.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/certifhighlysensitivedocument.pdf?sfvrsn=ba7fba09_4",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-memorandum-on-sealed-and-confidential-materials-53",
    label: "Memorandum on Sealed and Confidential Materials",
    category: "Sealed Material",
    fileName: "53-memorandum-on-sealed-and-confidential-materials.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/SealedConfidMem.pdf?sfvrsn=a9115af4_24",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-brief-appendix-requirements-54",
    label: "Brief & Appendix Requirements",
    category: "Formal Brief & Appendix",
    fileName: "54-brief-appendix-requirements.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/briefapxreq.pdf?sfvrsn=2876b509_15",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-brief-cover-page-appeals-55",
    label: "Brief Cover Page (Appeals)",
    category: "Formal Brief & Appendix",
    fileName: "55-brief-cover-page-appeals.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/brief-cover-page-district-court-appeals.pdf?sfvrsn=3b28cad4_12",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-brief-cover-page-agency-review-56",
    label: "Brief Cover Page (Agency Review)",
    category: "Formal Brief & Appendix",
    fileName: "56-brief-cover-page-agency-review.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/brief-cover-page-agency-review.pdf?sfvrsn=c6d25db7_10",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-appendix-pagination-brief-citation-guide-57",
    label: "Appendix Pagination & Brief Citation Guide",
    category: "Formal Brief & Appendix",
    fileName: "57-appendix-pagination-brief-citation-guide.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/appendixpagination-briefcitationguide.pdf?sfvrsn=1cc9b409_14",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-electronic-appendix-instructions-58",
    label: "Electronic Appendix Instructions",
    category: "Formal Brief & Appendix",
    fileName: "58-electronic-appendix-instructions.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/elecapx.pdf?sfvrsn=a13afdcb_42",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-appendix-cover-page-appeals-59",
    label: "Appendix Cover Page (Appeals)",
    category: "Formal Brief & Appendix",
    fileName: "59-appendix-cover-page-appeals.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/appendix-cover-page-district-court-appeals.pdf?sfvrsn=f54004c8_8",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-appendix-cover-page-agency-review-60",
    label: "Appendix Cover Page (Agency Review)",
    category: "Formal Brief & Appendix",
    fileName: "60-appendix-cover-page-agency-review.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/appendix-cover-page-agency-review.pdf?sfvrsn=f297adf3_10",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-certificate-of-compliance-with-type-volume-limit-61",
    label: "Certificate of Compliance with Type-Volume Limit",
    category: "Formal Brief & Appendix",
    fileName: "61-certificate-of-compliance-with-type-volume-limit.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/certcomp.pdf?sfvrsn=f377a509_27",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-certificate-for-highly-sensitive-document-protection-62",
    label: "Certificate for Highly Sensitive Document Protection",
    category: "Formal Brief & Appendix",
    fileName: "62-certificate-for-highly-sensitive-document-protection.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/certifhighlysensitivedocument.pdf?sfvrsn=ba7fba09_6",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-certificate-of-service-63",
    label: "Certificate of Service",
    category: "Formal Brief & Appendix",
    fileName: "63-certificate-of-service.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/certofservice.pdf?sfvrsn=eaadb909_12",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-certificate-of-service-of-anders-brief-64",
    label: "Certificate of Service of Anders Brief",
    category: "Formal Brief & Appendix",
    fileName: "64-certificate-of-service-of-anders-brief.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/certificate-of-service-of-anders-brief.pdf?sfvrsn=a13587c_8",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-notice-of-paper-or-manual-filing-65",
    label: "Notice of Paper or Manual Filing",
    category: "Formal Brief & Appendix",
    fileName: "65-notice-of-paper-or-manual-filing.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/notice-of-paper-filing.pdf?sfvrsn=5dcedfc8_18",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-informal-brief-habeas-and-2255-cases-66",
    label: "Informal Brief (Habeas and § 2255 Cases)",
    category: "Informal Brief",
    fileName: "66-informal-brief-habeas-and-2255-cases.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/informalbriefhc2255.pdf?sfvrsn=2ea8be88_18",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-informal-brief-other-pro-se-cases-67",
    label: "Informal Brief (Other Pro Se Cases)",
    category: "Informal Brief",
    fileName: "67-informal-brief-other-pro-se-cases.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/informalbrief.pdf?sfvrsn=2ea79077_18",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-notice-regarding-conflict-with-proposed-argument-dates-68",
    label: "Notice Regarding Conflict With Proposed Argument Dates",
    category: "Oral Argument",
    fileName: "68-notice-regarding-conflict-with-proposed-argument-dates.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/noticereconflictproposedargumentdate.pdf?sfvrsn=d2d1f40f_26",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-oral-argument-acknowledgment-69",
    label: "Oral Argument Acknowledgment",
    category: "Oral Argument",
    fileName: "69-oral-argument-acknowledgment.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/oralargumentacknowledgment.pdf?sfvrsn=7acde767_62",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-oral-argument-cd-request-70",
    label: "Oral Argument CD Request",
    category: "Oral Argument",
    fileName: "70-oral-argument-cd-request.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/oralargumentcdrequest.pdf?sfvrsn=759ab9eb_37",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-bill-of-costs-71",
    label: "Bill of Costs",
    category: "Costs & Sanctions",
    fileName: "71-bill-of-costs.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/costs.pdf?sfvrsn=310415d6_20",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-sanctions-payment-form-72",
    label: "Sanctions Payment Form",
    category: "Costs & Sanctions",
    fileName: "72-sanctions-payment-form.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/sanctionpaymentform.pdf?sfvrsn=429aa09_12",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-petition-for-writ-of-certiorari-information-sheet-73",
    label: "Petition for Writ of Certiorari Information Sheet",
    category: "Certiorari",
    fileName: "73-petition-for-writ-of-certiorari-information-sheet.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/certinfosheet.pdf?sfvrsn=5d35fe5a_14",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-certiorari-status-form-74",
    label: "Certiorari Status Form",
    category: "Certiorari",
    fileName: "74-certiorari-status-form.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/certioraristatusform.pdf?sfvrsn=f7bb02a4_20",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-sample-motion-to-withdraw-at-the-certiorari-stage-75",
    label: "Sample Motion to Withdraw at the Certiorari Stage",
    category: "Certiorari",
    fileName: "75-sample-motion-to-withdraw-at-the-certiorari-stage.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/motiontowithdrawascounsel--form.pdf?sfvrsn=102ae7c5_16",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-motion-for-authorization-to-file-successive-application-2244-76",
    label: "Motion for Authorization to File Successive Application (§ 2244)",
    category: "Post-Conviction Application",
    fileName: "76-motion-for-authorization-to-file-successive-application-2244.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/2244form.pdf?sfvrsn=d052ce91_38",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-petition-for-writ-of-habeas-corpus-2254-77",
    label: "Petition for Writ of Habeas Corpus (§ 2254)",
    category: "Post-Conviction Application",
    fileName: "77-petition-for-writ-of-habeas-corpus-2254.pdf",
    sourceUrl: "https://www.uscourts.gov/sites/default/files/AO_241_0.pdf",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-petition-for-writ-of-habeas-corpus-2241-78",
    label: "Petition for Writ of Habeas Corpus (§ 2241)",
    category: "Post-Conviction Application",
    fileName: "78-petition-for-writ-of-habeas-corpus-2241.pdf",
    sourceUrl: "https://www.uscourts.gov/sites/default/files/AO_242_0.pdf",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-motion-to-vacate-sentence-2255-79",
    label: "Motion to Vacate Sentence (§ 2255)",
    category: "Post-Conviction Application",
    fileName: "79-motion-to-vacate-sentence-2255.pdf",
    sourceUrl: "https://www.uscourts.gov/sites/default/files/AO_243_0.pdf",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-judicial-complaint-form-80",
    label: "Judicial Complaint Form",
    category: "Judicial Complaint",
    fileName: "80-judicial-complaint-form.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/judcomfm.pdf?sfvrsn=de143fb3_14",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-fourth-circuit-copy-request-form-81",
    label: "Fourth Circuit Copy Request Form",
    category: "Copies of Documents",
    fileName: "81-fourth-circuit-copy-request-form.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/copyrequest.pdf?sfvrsn=2ab3f4ff_21",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-national-archives-form-93-82",
    label: "National Archives Form 93",
    category: "Copies of Documents",
    fileName: "82-national-archives-form-93.pdf",
    sourceUrl: "https://www.archives.gov/research/court-records/form-93.pdf",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-oral-argument-cd-request-83",
    label: "Oral Argument CD Request",
    category: "Copies of Documents",
    fileName: "83-oral-argument-cd-request.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/oralargumentcdrequest.pdf?sfvrsn=759ab9eb_30",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
  {
    id: "ca4-request-for-electronic-record-outside-ecf-84",
    label: "Request for Electronic Record Outside ECF",
    category: "Copies of Documents",
    fileName: "84-request-for-electronic-record-outside-ecf.pdf",
    sourceUrl: "https://www.ca4.uscourts.gov/docs/pdfs/elecrecord-nonecfrequest.pdf?sfvrsn=5fbdb909_4",
    mediaType: 'application/pdf',
    sourceVersionId: ca4SourceVersionIds.ca4Forms2026,
  },
] satisfies Ca4FormTemplate[]

export const ca4FormTemplateById = new Map(
  ca4FormTemplates.map((template) => [template.id, template]),
)

function normalizeTemplateSearch(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
}

export function findCa4FormTemplate(value: string) {
  const normalized = normalizeTemplateSearch(value)
  return ca4FormTemplates.find((template) => {
    const label = normalizeTemplateSearch(template.label)
    return normalized === label || normalized.includes(label) || label.includes(normalized)
  })
}

